<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Version>1.0.1</Version>
		<AssemblyName>scope_gen</AssemblyName>		
		<Deterministic>true</Deterministic>		
		<Configurations>Debug;Release;Source</Configurations>		
		<RunPostBuildEvent>Always</RunPostBuildEvent>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="build_protocol.bat" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="gendll.bat" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\DeepMeta\DeepCore.Event.Debug\DeepCore.Event.Debug.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepCore.Event\DeepCore.Event.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepCore.Geometry\DeepCore.Geometry.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepCore.GUI\DeepCore.GUI.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepCore\DeepCore.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepCrystal\DeepCrystal.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepTools.CodeGen\DeepTools.CodeGen.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepTools.XLS2Lang\DeepTools.XLS2Lang.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepMetaGame.Data\DeepMetaGame.Data.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepMetaGame.Display\DeepMetaGame.Display.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepMetaGame.Host\DeepMetaGame.Host.csproj" />
		<ProjectReference Include="..\..\DeepMeta\DeepMetaGame.Slave\DeepMetaGame.Slave.csproj" />
		<ProjectReference Include="..\..\DeepMeta\Gate.Data\Gate.Data.csproj" />
		<ProjectReference Include="..\_Temp_.Battle\_Temp_.Battle.csproj" />
		<ProjectReference Include="..\_Temp_.Protocol\_Temp_.Protocol.csproj" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="gendll $(TargetPath)" />
	</Target>
</Project>